# Generated by Django 6.0.4 on 2026-07-15 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name': 'Настройки пользователя', 'verbose_name_plural': 'Настройки пользователей'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='trust_score',
            field=models.IntegerField(default=0, verbose_name='Уровень доверия'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='auto_skip_intro',
            field=models.BooleanField(default=False, help_text='Автоматически пропускать заставки', verbose_name='Автопропуск заставки'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='language_code',
            field=models.CharField(default='rus', help_text='Жесткое ограничение языка (например: rus, eng)', max_length=20, verbose_name='Код языка'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_voiceovers',
            field=models.JSONField(blank=True, default=list, help_text="Массив приоритетов (например: ['LostFilm', 'HDrezka'])", verbose_name='Приоритетные студии озвучки'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
