# Generated by Django 6.0.4 on 2026-04-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='preferred_language',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='language_code',
            field=models.CharField(default='rus', help_text='Жесткое ограничение языка (напр. rus, eng)', max_length=20),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='preferred_voiceovers',
            field=models.JSONField(blank=True, default=list, help_text="Массив приоритетов (напр. ['LostFilm', 'HDrezka'])"),
        ),
    ]
