# Generated by Django 6.0.4 on 2026-07-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KodikSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique identifier for the sync task', max_length=100, unique=True)),
                ('state_data', models.JSONField(default=dict, help_text='Stored state (e.g., next_page_url, last_index)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
