# Generated by Django 6.0.4 on 2026-07-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodik_plugin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KodikDumpProcessedID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kp_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('imdb_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('shiki_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('mdl_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
