# Generated by Django 6.0.4 on 2026-07-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodik_plugin', '0002_kodikdumpprocessedid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kodikdumpprocessedid',
            options={'verbose_name': 'Обработанный ID дампа Kodik', 'verbose_name_plural': 'Обработанные ID дампов Kodik'},
        ),
        migrations.AlterModelOptions(
            name='kodiksyncstate',
            options={'verbose_name': 'Состояние синхронизации Kodik', 'verbose_name_plural': 'Состояния синхронизации Kodik'},
        ),
        migrations.AlterField(
            model_name='kodikdumpprocessedid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата обработки'),
        ),
        migrations.AlterField(
            model_name='kodikdumpprocessedid',
            name='imdb_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='IMDb ID'),
        ),
        migrations.AlterField(
            model_name='kodikdumpprocessedid',
            name='kp_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Кинопоиск ID'),
        ),
        migrations.AlterField(
            model_name='kodikdumpprocessedid',
            name='mdl_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='MyDramaList ID'),
        ),
        migrations.AlterField(
            model_name='kodikdumpprocessedid',
            name='shiki_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Шикимори ID'),
        ),
        migrations.AlterField(
            model_name='kodiksyncstate',
            name='key',
            field=models.CharField(help_text='Unique identifier for the sync task', max_length=100, unique=True, verbose_name='Идентификатор задачи'),
        ),
        migrations.AlterField(
            model_name='kodiksyncstate',
            name='state_data',
            field=models.JSONField(default=dict, help_text='Stored state (e.g., next_page_url, last_index)', verbose_name='Данные состояния'),
        ),
        migrations.AlterField(
            model_name='kodiksyncstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
