# Generated by Django 6.0.4 on 2026-07-14 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_field', models.CharField(help_text="e.g., 'genre', 'type'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'source_field')},
            },
        ),
        migrations.CreateModel(
            name='TaxonomyItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('GENRE', 'Genre'), ('TAG', 'Tag'), ('TYPE', 'Type'), ('CATEGORY', 'Category')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='taxonomy.taxonomyitem')),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RawTermMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='taxonomy.rawterm')),
                ('taxonomy_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_mappings', to='taxonomy.taxonomyitem')),
            ],
            options={
                'unique_together': {('raw_term', 'taxonomy_item')},
            },
        ),
    ]
