# Generated by Django 6.0.4 on 2026-07-15 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_normalize_raw_terms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawterm',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сырой термин', 'verbose_name_plural': 'Сырые термины'},
        ),
        migrations.AlterModelOptions(
            name='rawtermmapping',
            options={'verbose_name': 'Связь сырого термина', 'verbose_name_plural': 'Связи сырых терминов'},
        ),
        migrations.AlterModelOptions(
            name='taxonomyitem',
            options={'ordering': ['type', 'name'], 'verbose_name': 'Элемент таксономии', 'verbose_name_plural': 'Элементы таксономии'},
        ),
        migrations.AlterField(
            model_name='rawterm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='rawterm',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название сырого термина'),
        ),
        migrations.AlterField(
            model_name='rawterm',
            name='source_field',
            field=models.CharField(help_text="e.g., 'genre', 'type'", max_length=100, verbose_name='Источник поля'),
        ),
        migrations.AlterField(
            model_name='rawtermmapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата связи'),
        ),
        migrations.AlterField(
            model_name='rawtermmapping',
            name='raw_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='taxonomy.rawterm', verbose_name='Сырой термин'),
        ),
        migrations.AlterField(
            model_name='rawtermmapping',
            name='taxonomy_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_mappings', to='taxonomy.taxonomyitem', verbose_name='Элемент таксономии'),
        ),
        migrations.AlterField(
            model_name='taxonomyitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='taxonomyitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='taxonomyitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='taxonomy.taxonomyitem', verbose_name='Родительский элемент'),
        ),
        migrations.AlterField(
            model_name='taxonomyitem',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='taxonomyitem',
            name='type',
            field=models.CharField(choices=[('GENRE', 'Жанр'), ('TAG', 'Тег'), ('TYPE', 'Тип'), ('CATEGORY', 'Категория')], max_length=20, verbose_name='Тип таксономии'),
        ),
    ]
