# Generated by Django 6.0.4 on 2026-04-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PluginProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название донора (напр. Kodik, Collaps)', max_length=100)),
                ('endpoint_url', models.URLField(help_text='URL эндпоинта плагина')),
                ('api_token', models.CharField(blank=True, help_text='Токен авторизации (если нужен)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Включен ли опрос этого плагина')),
                ('timeout', models.IntegerField(default=3, help_text='Таймаут ожидания ответа в секундах')),
            ],
        ),
    ]
