# Generated by Django 6.0.4 on 2026-04-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalContentRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='ID контента на стороне плагина', max_length=100)),
                ('content_type', models.CharField(choices=[('MANIFEST', 'External Manifest'), ('EPISODE_IFRAME', 'Episode iFrame'), ('ENTITY_IFRAME', 'Entity iFrame')], max_length=20)),
                ('target_asset_uuid', models.UUIDField(blank=True, help_text='UUID локального видео-ассета', null=True)),
                ('fetch_url', models.URLField(help_text='URL для запроса манифеста или iframe', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PluginProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название донора (напр. Kodik, Collaps)', max_length=100)),
                ('endpoint_url', models.URLField(help_text='URL эндпоинта плагина')),
                ('api_token', models.CharField(blank=True, help_text='Токен авторизации (если нужен)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Включен ли опрос этого плагина')),
                ('timeout', models.IntegerField(default=3, help_text='Таймаут ожидания ответа в секундах')),
                ('allowed_domains', models.JSONField(blank=True, default=list, help_text="Список разрешенных хостов (напр. ['anime-gate.ru']). Пусто = глобально")),
                ('webhook_secret', models.CharField(blank=True, help_text='Секрет для подтверждения WebHook-ов от плагина', max_length=255)),
                ('can_restore_assets', models.BooleanField(default=False, help_text='Может ли плагин заменять удаленные локальные видео-ассеты (Lifeboat)?')),
            ],
        ),
    ]
