# Generated by Django 6.0.4 on 2026-04-24 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
        ('content', '0004_title_kp_id_title_mal_id_title_mdl_id_title_shiki_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginprovider',
            name='allowed_domains',
            field=models.JSONField(blank=True, default=list, help_text="Список разрешенных хостов (напр. ['anime-gate.ru']). Пусто = глобально"),
        ),
        migrations.AddField(
            model_name='pluginprovider',
            name='can_restore_assets',
            field=models.BooleanField(default=False, help_text='Может ли плагин заменять удаленные локальные видео-ассеты (Lifeboat)?'),
        ),
        migrations.AddField(
            model_name='pluginprovider',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='Секрет для подтверждения WebHook-ов от плагина', max_length=255),
        ),
        migrations.CreateModel(
            name='ExternalContentRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='ID контента на стороне плагина', max_length=100)),
                ('content_type', models.CharField(choices=[('MANIFEST', 'External Manifest'), ('EPISODE_IFRAME', 'Episode iFrame'), ('ENTITY_IFRAME', 'Entity iFrame')], max_length=20)),
                ('target_asset_uuid', models.UUIDField(blank=True, help_text='UUID локального видео-ассета', null=True)),
                ('fetch_url', models.URLField(help_text='URL для запроса манифеста или iframe', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_content', to='content.episode')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registry_entries', to='aggregator.pluginprovider')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_content', to='content.title')),
            ],
            options={
                'unique_together': {('plugin', 'title', 'episode', 'content_type', 'target_asset_uuid')},
            },
        ),
    ]
