# Generated by Django 6.0.4 on 2026-04-30 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aggregator', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcontentregistry',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_content', to='content.episode'),
        ),
        migrations.AddField(
            model_name='externalcontentregistry',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_content', to='content.title'),
        ),
        migrations.AddField(
            model_name='externalcontentregistry',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registry_entries', to='aggregator.pluginprovider'),
        ),
        migrations.AlterUniqueTogether(
            name='externalcontentregistry',
            unique_together={('plugin', 'title', 'episode', 'content_type', 'target_asset_uuid')},
        ),
    ]
