# Generated by Django 6.0.4 on 2026-07-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pluginprovider',
            name='can_restore_assets',
        ),
    ]
