# Generated by Django 6.0.4 on 2026-07-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0003_remove_pluginprovider_can_restore_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginprovider',
            name='allow_title_creation',
            field=models.BooleanField(default=False, help_text='Разрешает плагину создавать новые тайтлы и эпизоды'),
        ),
        migrations.AddField(
            model_name='pluginprovider',
            name='allow_title_update',
            field=models.BooleanField(default=False, help_text='Разрешает плагину обновлять метаданные существующих тайтлов'),
        ),
        migrations.AddField(
            model_name='pluginprovider',
            name='metadata_priority',
            field=models.IntegerField(default=0, help_text='Приоритет метаданных плагина. Чем выше, тем авторитетнее источник'),
        ),
    ]
