# Generated by Django 6.0.4 on 2026-07-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0004_pluginprovider_allow_title_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginprovider',
            name='app_label',
            field=models.CharField(blank=True, help_text="Имя Django-приложения локального плагина (напр. 'kodik_plugin')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pluginprovider',
            name='is_local',
            field=models.BooleanField(default=False, help_text='Выполняется ли этот плагин локально внутри JCP?'),
        ),
        migrations.AlterField(
            model_name='pluginprovider',
            name='endpoint_url',
            field=models.URLField(blank=True, help_text='URL эндпоинта плагина (если удаленный)', null=True),
        ),
    ]
