# Generated by Django 6.0.4 on 2026-07-15 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0005_pluginprovider_app_label_pluginprovider_is_local_and_more'),
        ('content', '0010_title_raw_terms'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalcontentregistry',
            options={'verbose_name': 'Реестр внешнего контента', 'verbose_name_plural': 'Реестры внешнего контента'},
        ),
        migrations.AlterModelOptions(
            name='pluginprovider',
            options={'verbose_name': 'Провайдер плагина', 'verbose_name_plural': 'Провайдеры плагинов'},
        ),
        migrations.AddField(
            model_name='pluginprovider',
            name='client_script_url',
            field=models.URLField(blank=True, help_text='URL JavaScript файла плагина для отслеживания телеметрии на фронтенде', null=True, verbose_name='URL клиентского скрипта'),
        ),
        migrations.AlterField(
            model_name='externalcontentregistry',
            name='content_type',
            field=models.CharField(choices=[('MANIFEST', 'Внешний манифест'), ('EPISODE_IFRAME', 'iFrame серии'), ('ENTITY_IFRAME', 'iFrame произведения')], max_length=20, verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='externalcontentregistry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='externalcontentregistry',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_content', to='content.episode', verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='externalcontentregistry',
            name='external_id',
            field=models.CharField(help_text='ID контента на стороне плагина', max_length=100, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='externalcontentregistry',
            name='fetch_url',
            field=models.URLField(help_text='URL для запроса манифеста или iframe', max_length=500, verbose_name='URL источника'),
        ),
        migrations.AlterField(
            model_name='externalcontentregistry',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registry_entries', to='aggregator.pluginprovider', verbose_name='Плагин'),
        ),
        migrations.AlterField(
            model_name='externalcontentregistry',
            name='target_asset_uuid',
            field=models.UUIDField(blank=True, help_text='UUID локального видео-ассета', null=True, verbose_name='UUID локального ассета'),
        ),
        migrations.AlterField(
            model_name='externalcontentregistry',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_content', to='content.title', verbose_name='Произведение'),
        ),
        migrations.AlterField(
            model_name='externalcontentregistry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='pluginprovider',
            name='allow_title_creation',
            field=models.BooleanField(default=False, help_text='Разрешает плагину создавать новые тайтлы и серии', verbose_name='Создание произведений'),
        ),
        migrations.AlterField(
            model_name='pluginprovider',
            name='allow_title_update',
            field=models.BooleanField(default=False, help_text='Разрешает плагину обновлять метаданные существующих тайтлов', verbose_name='Обновление произведений'),
        ),
        migrations.AlterField(
            model_name='pluginprovider',
            name='allowed_domains',
            field=models.JSONField(blank=True, default=list, help_text="Список разрешенных хостов (например: ['anime-gate.ru']). Пусто = глобально", verbose_name='Разрешенные домены'),
        ),
        migrations.AlterField(
            model_name='pluginprovider',
            name='api_token',
            field=models.CharField(blank=True, help_text='Токен авторизации (если нужен)', max_length=255, verbose_name='Токен авторизации'),
        ),
        migrations.AlterField(
            model_name='pluginprovider',
            name='app_label',
            field=models.CharField(blank=True, help_text="Имя Django-приложения локального плагина (например: 'kodik_plugin')", max_length=100, null=True, verbose_name=' Django-приложение'),
        ),
        migrations.AlterField(
            model_name='pluginprovider',
            name='endpoint_url',
            field=models.URLField(blank=True, help_text='URL эндпоинта плагина (если удаленный)', null=True, verbose_name='URL эндпоинта'),
        ),
        migrations.AlterField(
            model_name='pluginprovider',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Включен ли опрос этого плагина', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='pluginprovider',
            name='is_local',
            field=models.BooleanField(default=False, help_text='Выполняется ли этот плагин локально внутри JCP?', verbose_name='Локальное выполнение'),
        ),
        migrations.AlterField(
            model_name='pluginprovider',
            name='metadata_priority',
            field=models.IntegerField(default=0, help_text='Приоритет метаданных плагина. Чем выше, тем авторитетнее источник', verbose_name='Приоритет метаданных'),
        ),
        migrations.AlterField(
            model_name='pluginprovider',
            name='name',
            field=models.CharField(help_text='Название донора (например: Kodik, Collaps)', max_length=100, verbose_name='Название донора'),
        ),
        migrations.AlterField(
            model_name='pluginprovider',
            name='timeout',
            field=models.IntegerField(default=3, help_text='Таймаут ожидания ответа в секундах', verbose_name='Таймаут (сек)'),
        ),
        migrations.AlterField(
            model_name='pluginprovider',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='Секрет для подтверждения WebHook-ов от плагина', max_length=255, verbose_name='Секрет вебхука'),
        ),
        migrations.CreateModel(
            name='ViewingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(db_index=True, max_length=255, verbose_name='ID объекта')),
                ('expires_at', models.DateTimeField(verbose_name='Срок истечения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия просмотра',
                'verbose_name_plural': 'Сессии просмотра',
            },
        ),
    ]
