# Generated by Django 6.0.4 on 2026-04-30 05:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season_number', models.IntegerField(default=1)),
                ('episode_number', models.IntegerField(default=1)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['season_number', 'episode_number'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('MOVIE', 'Movie'), ('SERIES', 'Series')], default='MOVIE', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20)),
                ('tmdb_id', models.CharField(blank=True, max_length=20)),
                ('kp_id', models.CharField(blank=True, max_length=20)),
                ('shiki_id', models.CharField(blank=True, max_length=20)),
                ('mal_id', models.CharField(blank=True, max_length=20)),
                ('mdl_id', models.CharField(blank=True, max_length=20)),
                ('wa_id', models.CharField(blank=True, max_length=20)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('rating_score', models.FloatField(db_index=True, default=0.0)),
                ('votes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TitleRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Version', help_text="Например: Театральная версия, Director's Cut", max_length=100)),
                ('author', models.CharField(blank=True, help_text='Релиз-группа или автор видео-сборки (напр. YIFY, HQCLUB)', max_length=100)),
                ('object_id', models.CharField(db_index=True, max_length=36)),
                ('rating_score', models.FloatField(default=0.0)),
                ('votes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackGroupRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_audio_asset_id', models.UUIDField(blank=True, help_text='ID конкретного Asset аудио', null=True)),
                ('last_audio_track_name', models.CharField(blank=True, help_text='Точная строка названия дорожки', max_length=255, null=True)),
                ('last_quality_label', models.CharField(blank=True, help_text='Напр: 1080p', max_length=50, null=True)),
                ('progress_ms', models.PositiveIntegerField(default=0, help_text='Current playback position in milliseconds')),
                ('is_completed', models.BooleanField(default=False, help_text='True if watched till the end credits')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(default='Unknown', help_text='Например: rus, eng, jpn', max_length=50)),
                ('author', models.CharField(blank=True, help_text='Студия озвучки или переводчик (напр. LostFilm, HDrezka)', max_length=100)),
                ('offset_ms', models.IntegerField(default=0, help_text='Сдвиг для синхронизации в миллисекундах')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='media.asset')),
            ],
        ),
    ]
