# Generated by Django 6.0.4 on 2026-04-30 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aggregator', '0002_initial'),
        ('content', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='title',
            name='genres',
            field=models.ManyToManyField(blank=True, to='content.genre'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='content.title'),
        ),
        migrations.AddField(
            model_name='episode',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='content.title'),
        ),
        migrations.AddField(
            model_name='titlerating',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='content.title'),
        ),
        migrations.AddField(
            model_name='titlerating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trackgroup',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='trackgroup',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Provider that created this track group. Null means local Hub/Node.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_groups', to='aggregator.pluginprovider'),
        ),
        migrations.AddField(
            model_name='trackgroup',
            name='video_asset',
            field=models.ForeignKey(limit_choices_to={'type': 'VIDEO'}, on_delete=django.db.models.deletion.RESTRICT, related_name='track_groups', to='media.asset'),
        ),
        migrations.AddField(
            model_name='additionaltrack',
            name='track_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_tracks', to='content.trackgroup'),
        ),
        migrations.AddField(
            model_name='trackgrouprating',
            name='track_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='content.trackgroup'),
        ),
        migrations.AddField(
            model_name='trackgrouprating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.episode'),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='content.title'),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='track_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.trackgroup'),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('title', 'season_number', 'episode_number')},
        ),
        migrations.AlterUniqueTogether(
            name='titlerating',
            unique_together={('user', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='trackgrouprating',
            unique_together={('user', 'track_group')},
        ),
        migrations.AlterUniqueTogether(
            name='watchhistory',
            unique_together={('user', 'title')},
        ),
    ]
