# Generated by Django 6.0.4 on 2026-04-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchhistory',
            name='last_audio_asset_id',
            field=models.UUIDField(blank=True, help_text='ID конкретного Asset аудио', null=True),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='last_quality_label',
            field=models.CharField(blank=True, help_text='Напр: 1080p', max_length=50, null=True),
        ),
    ]
