# Generated by Django 6.0.4 on 2026-04-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_watchhistory_last_audio_asset_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='kp_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='title',
            name='mal_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='title',
            name='mdl_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='title',
            name='shiki_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='title',
            name='wa_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
