# Generated by Django 6.0.4 on 2026-07-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_trackgroup_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='metadata_priority_level',
            field=models.IntegerField(default=0, help_text='Приоритет последнего обновившего источника'),
        ),
        migrations.AddField(
            model_name='title',
            name='metadata_priority_level',
            field=models.IntegerField(default=0, help_text='Приоритет последнего обновившего источника'),
        ),
    ]
