# Generated by Django 6.0.4 on 2026-07-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_episode_metadata_priority_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='title',
            name='kp_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='title',
            name='mal_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='title',
            name='mdl_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='title',
            name='original_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='title',
            name='shiki_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='title',
            name='tmdb_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='title',
            name='wa_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
