# Generated by Django 6.0.4 on 2026-04-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchhistory',
            name='last_audio_track_name',
            field=models.CharField(blank=True, help_text='Точная строка названия дорожки', max_length=255, null=True),
        ),
    ]
