# Generated by Django 6.0.4 on 2026-07-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_title_imdb_id_alter_title_kp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='poster_url',
            field=models.URLField(blank=True, help_text='Предыдущий успешно загруженный URL постера', max_length=512, null=True),
        ),
    ]
