# Generated by Django 6.0.4 on 2026-04-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_watchhistory_last_audio_track_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaltrack',
            name='author',
            field=models.CharField(blank=True, help_text='Студия озвучки или переводчик (напр. LostFilm, HDrezka)', max_length=100),
        ),
        migrations.AddField(
            model_name='trackgroup',
            name='author',
            field=models.CharField(blank=True, help_text='Релиз-группа или автор видео-сборки (напр. YIFY, HQCLUB)', max_length=100),
        ),
        migrations.AlterField(
            model_name='additionaltrack',
            name='language',
            field=models.CharField(default='Unknown', help_text='Например: rus, eng, jpn', max_length=50),
        ),
    ]
