# Generated by Django 6.0.4 on 2026-07-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_title_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
