# Generated by Django 6.0.4 on 2026-04-27 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_pluginprovider_allowed_domains_and_more'),
        ('content', '0007_additionaltrack_author_trackgroup_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackgroup',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Provider that created this track group. Null means local Hub/Node.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_groups', to='aggregator.pluginprovider'),
        ),
    ]
