# Generated by Django 6.0.4 on 2026-07-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_title_updated_at'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='taxonomy_items',
            field=models.ManyToManyField(blank=True, to='taxonomy.taxonomyitem'),
        ),
    ]
