# Generated by Django 6.0.4 on 2026-04-27 06:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_trackgroup_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='title',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trackgroup',
            name='object_id',
            field=models.CharField(db_index=True, max_length=36),
        ),
    ]
