# Generated by Django 6.0.4 on 2026-07-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_data_migrate_taxonomy'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='raw_terms',
            field=models.ManyToManyField(blank=True, help_text='Сырые термины от доноров', to='taxonomy.rawterm'),
        ),
    ]
