# Generated by Django 6.0.4 on 2026-07-15 16:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_title_raw_terms'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('media', '0002_remove_asset_provider'),
        ('taxonomy', '0003_alter_rawterm_options_alter_rawtermmapping_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionaltrack',
            options={'verbose_name': 'Дополнительная дорожка', 'verbose_name_plural': 'Дополнительные дорожки'},
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['season_number', 'episode_number'], 'verbose_name': 'Серия', 'verbose_name_plural': 'Серии'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AlterModelOptions(
            name='titlerating',
            options={'verbose_name': 'Оценка произведения', 'verbose_name_plural': 'Оценки произведений'},
        ),
        migrations.AlterModelOptions(
            name='trackgroup',
            options={'verbose_name': 'Группа дорожек', 'verbose_name_plural': 'Группы дорожек'},
        ),
        migrations.AlterModelOptions(
            name='trackgrouprating',
            options={'verbose_name': 'Оценка группы дорожек', 'verbose_name_plural': 'Оценки групп дорожек'},
        ),
        migrations.AlterModelOptions(
            name='watchhistory',
            options={'ordering': ['-updated_at'], 'verbose_name': 'История просмотра', 'verbose_name_plural': 'История просмотров'},
        ),
        migrations.AlterField(
            model_name='additionaltrack',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='media.asset', verbose_name='Ресурс'),
        ),
        migrations.AlterField(
            model_name='additionaltrack',
            name='author',
            field=models.CharField(blank=True, help_text='Студия озвучки или переводчик (например, LostFilm, HDrezka)', max_length=100, verbose_name='Студия озвучки'),
        ),
        migrations.AlterField(
            model_name='additionaltrack',
            name='language',
            field=models.CharField(default='Unknown', help_text='Например: rus, eng, jpn', max_length=50, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='additionaltrack',
            name='offset_ms',
            field=models.IntegerField(default=0, help_text='Сдвиг для синхронизации в миллисекундах', verbose_name='Смещение (мс)'),
        ),
        migrations.AlterField(
            model_name='additionaltrack',
            name='track_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_tracks', to='content.trackgroup', verbose_name='Группа дорожек'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.IntegerField(default=1, verbose_name='Номер серии'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='metadata_priority_level',
            field=models.IntegerField(default=0, help_text='Приоритет последнего обновившего источника', verbose_name='Приоритет метаданных'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='season_number',
            field=models.IntegerField(default=1, verbose_name='Номер сезона'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='content.title', verbose_name='Произведение'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='content.title', verbose_name='Произведение'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='title',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='title',
            name='genres',
            field=models.ManyToManyField(blank=True, to='content.genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='title',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='IMDb ID'),
        ),
        migrations.AlterField(
            model_name='title',
            name='kp_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кинопоиск ID'),
        ),
        migrations.AlterField(
            model_name='title',
            name='mal_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='MAL ID'),
        ),
        migrations.AlterField(
            model_name='title',
            name='mdl_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='MDL ID'),
        ),
        migrations.AlterField(
            model_name='title',
            name='metadata_priority_level',
            field=models.IntegerField(default=0, help_text='Приоритет последнего обновившего источника', verbose_name='Уровень приоритета метаданных'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='title',
            name='original_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Оригинальное название'),
        ),
        migrations.AlterField(
            model_name='title',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='title',
            name='poster_url',
            field=models.URLField(blank=True, help_text='Предыдущий успешно загруженный URL постера', max_length=512, null=True, verbose_name='URL постера'),
        ),
        migrations.AlterField(
            model_name='title',
            name='rating_score',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='title',
            name='raw_terms',
            field=models.ManyToManyField(blank=True, help_text='Сырые термины от доноров', to='taxonomy.rawterm', verbose_name='Сырые термины'),
        ),
        migrations.AlterField(
            model_name='title',
            name='release_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='title',
            name='shiki_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Shikimori ID'),
        ),
        migrations.AlterField(
            model_name='title',
            name='taxonomy_items',
            field=models.ManyToManyField(blank=True, to='taxonomy.taxonomyitem', verbose_name='Элементы таксономии'),
        ),
        migrations.AlterField(
            model_name='title',
            name='tmdb_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='TMDb ID'),
        ),
        migrations.AlterField(
            model_name='title',
            name='type',
            field=models.CharField(choices=[('MOVIE', 'Фильм'), ('SERIES', 'Сериал')], default='MOVIE', max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='title',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='title',
            name='votes_count',
            field=models.IntegerField(default=0, verbose_name='Количество голосов'),
        ),
        migrations.AlterField(
            model_name='title',
            name='wa_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='WorldArt ID'),
        ),
        migrations.AlterField(
            model_name='titlerating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='titlerating',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='titlerating',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='content.title', verbose_name='Произведение'),
        ),
        migrations.AlterField(
            model_name='titlerating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='titlerating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='trackgroup',
            name='author',
            field=models.CharField(blank=True, help_text='Релиз-группа или автор видео-сборки (например, YIFY, HQCLUB)', max_length=100, verbose_name='Автор/Релиз-группа'),
        ),
        migrations.AlterField(
            model_name='trackgroup',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='trackgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='trackgroup',
            name='name',
            field=models.CharField(default='Default Version', help_text="Например: Театральная версия, Director's Cut", max_length=100, verbose_name='Название версии'),
        ),
        migrations.AlterField(
            model_name='trackgroup',
            name='object_id',
            field=models.CharField(db_index=True, max_length=36, verbose_name='ID объекта'),
        ),
        migrations.AlterField(
            model_name='trackgroup',
            name='rating_score',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='trackgroup',
            name='video_asset',
            field=models.ForeignKey(limit_choices_to={'type': 'VIDEO'}, on_delete=django.db.models.deletion.RESTRICT, related_name='track_groups', to='media.asset', verbose_name='Видео ресурс'),
        ),
        migrations.AlterField(
            model_name='trackgroup',
            name='votes_count',
            field=models.IntegerField(default=0, verbose_name='Количество голосов'),
        ),
        migrations.AlterField(
            model_name='trackgrouprating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='trackgrouprating',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='trackgrouprating',
            name='track_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='content.trackgroup', verbose_name='Группа дорожек'),
        ),
        migrations.AlterField(
            model_name='trackgrouprating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='trackgrouprating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.episode', verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Установите в True, если просмотр завершен', verbose_name='Просмотр завершен'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='last_audio_asset_id',
            field=models.UUIDField(blank=True, help_text='ID конкретного Asset аудио', null=True, verbose_name='ID аудиоресурса'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='last_audio_track_name',
            field=models.CharField(blank=True, help_text='Точная строка названия дорожки', max_length=255, null=True, verbose_name='Название аудиодорожки'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='last_quality_label',
            field=models.CharField(blank=True, help_text='Например: 1080p', max_length=50, null=True, verbose_name='Качество'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='progress_ms',
            field=models.PositiveIntegerField(default=0, help_text='Текущая позиция воспроизведения в миллисекундах', verbose_name='Прогресс (мс)'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='content.title', verbose_name='Произведение'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='track_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.trackgroup', verbose_name='Группа дорожек'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='EpisodeWatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_ms', models.PositiveIntegerField(default=0, help_text='Текущая позиция воспроизведения в миллисекундах', verbose_name='Прогресс (мс)')),
                ('is_completed', models.BooleanField(default=False, help_text='Установите в True, если просмотр завершен', verbose_name='Просмотр завершен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='content.episode', verbose_name='Серия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_watch_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История просмотра серии',
                'verbose_name_plural': 'Истории просмотра серий',
                'unique_together': {('user', 'episode')},
            },
        ),
    ]
