# Generated by Django 6.0.4 on 2026-07-17 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_additionaltrack_options_alter_episode_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='episodewatchhistory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='watchhistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='episodewatchhistory',
            name='guest_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID гостя'),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='guest_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID гостя'),
        ),
        migrations.AlterField(
            model_name='episodewatchhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode_watch_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='episodewatchhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'episode'), name='unique_user_episode_history'),
        ),
        migrations.AddConstraint(
            model_name='episodewatchhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_id__isnull', False)), fields=('guest_id', 'episode'), name='unique_guest_episode_history'),
        ),
        migrations.AddConstraint(
            model_name='watchhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'title'), name='unique_user_title_history'),
        ),
        migrations.AddConstraint(
            model_name='watchhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_id__isnull', False)), fields=('guest_id', 'title'), name='unique_guest_title_history'),
        ),
    ]
