# Generated by Django 6.0.4 on 2026-04-30 05:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(help_text='Stream index in the original file')),
                ('codec_type', models.CharField(choices=[('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('SUBTITLE', 'Subtitle'), ('OTHER', 'Other')], max_length=20)),
                ('codec_name', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('extra_info', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['raw_file', 'index'],
            },
        ),
        migrations.CreateModel(
            name='RawMediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='raw_uploads/')),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Analysis'), ('ANALYZING', 'Analyzing via FFprobe'), ('READY', 'Ready for Extraction'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('metadata', models.JSONField(blank=True, help_text='FFprobe output', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranscodingPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напр: 4K AV1 5M', max_length=100, unique=True)),
                ('type', models.CharField(choices=[('VIDEO', 'Video'), ('AUDIO', 'Audio')], max_length=10)),
                ('codec', models.CharField(help_text='libx264, libaom-av1, libopus, aac...', max_length=50)),
                ('video_preset', models.CharField(blank=True, help_text='veryfast, fast, medium... (оставьте пустым для AV1)', max_length=50)),
                ('container', models.CharField(default='m3u8', help_text='m3u8, mp4, m4a, webm, ogg...', max_length=20)),
                ('bitrate', models.CharField(help_text='5M, 2M, 128k...', max_length=20)),
                ('width', models.IntegerField(blank=True, help_text='Для видео (напр. 3840)', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Применять ли этот пресет автоматически в Визарде')),
                ('custom_pre_args', models.TextField(blank=True, help_text='Аргументы ДО -i (input)')),
                ('custom_post_args', models.TextField(blank=True, help_text='Аргументы ПОСЛЕ кодеков')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('SUBTITLE', 'Subtitle')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(blank=True, help_text='Provider owning this asset. Null means local (Node) asset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='aggregator.pluginprovider')),
                ('source_stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_assets', to='media.mediastream')),
            ],
        ),
        migrations.AddField(
            model_name='mediastream',
            name='raw_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='media.rawmediafile'),
        ),
        migrations.CreateModel(
            name='AssetVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quality_label', models.CharField(blank=True, help_text='Напр: FHD x264 4M', max_length=50)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('READY', 'Ready'), ('ERROR', 'Error')], default='PROCESSING', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress in percent')),
                ('storage_path', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='media.asset')),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.transcodingpreset')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='mediastream',
            unique_together={('raw_file', 'index')},
        ),
    ]
