# Generated by Django 6.0.4 on 2026-04-21 06:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(help_text='Stream index in the original file')),
                ('codec_type', models.CharField(choices=[('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('SUBTITLE', 'Subtitle'), ('OTHER', 'Other')], max_length=20)),
                ('codec_name', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('extra_info', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['raw_file', 'index'],
            },
        ),
        migrations.CreateModel(
            name='RawMediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='raw_uploads/')),
                ('original_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Analysis'), ('ANALYZING', 'Analyzing via FFprobe'), ('READY', 'Ready for Extraction'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('metadata', models.JSONField(blank=True, help_text='FFprobe output', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('VIDEO', 'Video (HLS/MP4)'), ('AUDIO', 'Audio (AAC/M4A)'), ('SUBTITLE', 'Subtitle (VTT/SRT)')], max_length=20)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('READY', 'Ready'), ('ERROR', 'Error')], default='PROCESSING', max_length=20)),
                ('storage_path', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_assets', to='media.mediastream')),
            ],
        ),
        migrations.AddField(
            model_name='mediastream',
            name='raw_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='media.rawmediafile'),
        ),
        migrations.AlterUniqueTogether(
            name='mediastream',
            unique_together={('raw_file', 'index')},
        ),
    ]
