# Generated by Django 6.0.4 on 2026-04-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='progress',
            field=models.IntegerField(default=0, help_text='Progress in percent'),
        ),
    ]
