# Generated by Django 6.0.4 on 2026-07-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='provider',
        ),
    ]
