# Generated by Django 6.0.4 on 2026-04-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_asset_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmediafile',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
