# Generated by Django 6.0.4 on 2026-04-21 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_rawmediafile_original_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscodingPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напр: 4K AV1 5M', max_length=100, unique=True)),
                ('type', models.CharField(choices=[('VIDEO', 'Video'), ('AUDIO', 'Audio')], max_length=10)),
                ('codec', models.CharField(help_text='libx264, libaom-av1, libopus, aac...', max_length=50)),
                ('bitrate', models.CharField(help_text='5M, 2M, 128k...', max_length=20)),
                ('width', models.IntegerField(blank=True, help_text='Для видео (напр. 3840)', null=True)),
                ('custom_pre_args', models.TextField(blank=True, help_text='Аргументы ДО -i (input)')),
                ('custom_post_args', models.TextField(blank=True, help_text='Аргументы ПОСЛЕ кодеков')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='quality_label',
            field=models.CharField(blank=True, help_text='Копируется из пресета для плеера', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.transcodingpreset'),
        ),
    ]
