# Generated by Django 6.0.4 on 2026-04-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_transcodingpreset_asset_quality_label_asset_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcodingpreset',
            name='container',
            field=models.CharField(default='m3u8', help_text='m3u8, mp4, m4a, webm, ogg...', max_length=20),
        ),
        migrations.AddField(
            model_name='transcodingpreset',
            name='video_preset',
            field=models.CharField(blank=True, help_text='veryfast, fast, medium... (оставьте пустым для AV1)', max_length=50),
        ),
    ]
