# Generated by Django 6.0.4 on 2026-04-22 09:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_transcodingpreset_container_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='preset',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='quality_label',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='status',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='storage_path',
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('SUBTITLE', 'Subtitle')], max_length=20),
        ),
        migrations.CreateModel(
            name='AssetVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quality_label', models.CharField(blank=True, help_text='Напр: FHD x264 4M', max_length=50)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('READY', 'Ready'), ('ERROR', 'Error')], default='PROCESSING', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress in percent')),
                ('storage_path', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='media.asset')),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.transcodingpreset')),
            ],
        ),
    ]
