# Generated by Django 6.0.4 on 2026-04-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_remove_asset_preset_remove_asset_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcodingpreset',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Применять ли этот пресет автоматически в Визарде'),
        ),
    ]
