# Generated by Django 6.0.4 on 2026-04-27 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_pluginprovider_allowed_domains_and_more'),
        ('media', '0007_transcodingpreset_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Provider owning this asset. Null means local (Node) asset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='aggregator.pluginprovider'),
        ),
    ]
