# Generated by Django 6.0.4 on 2026-07-17 04:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterestProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID гостя')),
                ('taxonomy_distribution', models.JSONField(blank=True, default=dict, help_text='JSON вида {taxonomy_item_slug: accumulated_weight}', verbose_name='Распределение таксономии')),
                ('type_distribution', models.JSONField(blank=True, default=dict, help_text="JSON вида {'MOVIE': weight, 'SERIES': weight}", verbose_name='Распределение типов')),
                ('year_distribution', models.JSONField(blank=True, default=dict, help_text="JSON вида {'modern': weight, '2010s': weight, ...}", verbose_name='Распределение годов')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль интересов',
                'verbose_name_plural': 'Профили интересов',
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='unique_user_profile'), models.UniqueConstraint(condition=models.Q(('guest_id__isnull', False)), fields=('guest_id',), name='unique_guest_profile')],
            },
        ),
    ]
